# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Application security testing@2020
  inputs:
    projectName: 'hakancx'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'bookstore1'
    fullTeamName: 'CxServer'
    scanTimeout: '90'
    denyProject: true
    comment: 'Dhy_Azure_PoC'
    vulnerabilityThreshold: true
    high: '2'
    medium: '5'
    low: '10'
    enableDependencyScan: false
    incScan: false
    
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
